version: '3.2'
services:
    traefik:
        image: traefik:1.7.3
        restart: always
        command: --api --docker
        ports:
            - "80:80"     # Le port HTTP
            - "443:443"   # Le port HTTPS
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock 
            - ./conf/traefik.toml:/traefik.toml
            - ./conf/acme.json:/acme.json
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_network"
            - "traefik.port=8080"
            - "traefik.entryPoint=https"
            - "traefik.backend=traefik"
            - "traefik.frontend.rule=Host:domain.com"
        networks:
            - traefik_network
    

    whoami:
        image: containous/whoami
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_network"
            - "traefik.entryPoint=https"
            - "traefik.backend=whoami"
            - "traefik.frontend.rule=Host:first.container.domain.com"
        networks:
            - traefik_network

    whoami2:
        image: containous/whoami
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_network"
            - "traefik.entryPoint=https"
            - "traefik.backend=whoami2"
            - "traefik.frontend.rule=Host:second.container.domain.com"
        networks:
            - traefik_network
networks:
    traefik_network:
        external: true
